{% set name = "python-openstackclient" %}
{% set version = "6.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbef1ed34829c41052b2eca26480e29ca1f72be058d1430da5341ec44c4f295c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openstack = openstackclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python >=3.8
    - setuptools
  run:    
    - cryptography >=2.7
    - cliff >=3.5.0
    - iso8601 >=0.1.11
    - openstacksdk >=2.0.0
    - osc-lib >=2.3.0
    - oslo.i18n >=3.15.3
    - python-keystoneclient >=3.22.0
    - python-novaclient >=18.1.0
    - python-cinderclient>=3.3.0
    - stevedore>=2.0.1
    - python >=3.8
    - setuptools

test:
  imports:
    - openstackclient
  commands:
    - openstack --help


about:
  home: https://docs.openstack.org/python-openstackclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Client for OpenStack services
  doc_url: https://docs.openstack.org/python-openstackclient/latest/
  dev_url: https://opendev.org/openstack/python-openstackclient

extra:
  recipe-maintainers:
    - tschoonj
