{% set name = "python-openstackclient" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c53abe1b73b453f59da7b73679c3b759b48e51b8b054864b5fdea2ea82727d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openstack = openstackclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python >=3.8
    - setuptools
  run:
    - cliff >=3.5.0
    - iso8601 >=0.1.11
    - openstacksdk >=0.53.0
    - osc-lib >=2.3.0
    - oslo.i18n >=3.15.3
    - oslo.utils >=3.33.0
    - python >=3.8
    - python-keystoneclient >=3.22.0
    - python-novaclient >=17.0.0
    - python-cinderclient >=3.3.0
    - stevedore >=2.0.1
    - setuptools

test:
  imports:
    - openstackclient
  commands:
    - openstack --help


about:
  home: https://docs.openstack.org/python-openstackclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Client for OpenStack services
  doc_url: https://docs.openstack.org/python-openstackclient/latest/
  dev_url: https://opendev.org/openstack/python-openstackclient

extra:
  recipe-maintainers:
    - tschoonj
